### ISSUE TITLE
Use & support bosh java package vendoring

### ISSUE THREAD

**Issue by gberche-orange** [cloudfoundry/java-buildpack-release#2]
The bosh [package vendoring](https://bosh.io/docs/package-vendoring/) targets the bosh release authors that need to use language runtimes such as the Java JDK and Java JRE.

Currently, the Java experience for bosh release authors is suboptimal as:
   * the java package vendor is currently only providing the JRE and not yet JDK, see https://github.com/bosh-packages/java-release/issues/5
   * the java JDK build process at 
https://github.com/bosh-packages/java-release/blob/cc69e964ef0b8bae4395e4c91f175b2b654ea126/packages/openjdk-8/build.sh#L30-L64 differs from the mature java-buildpack JDK build process at 
https://github.com/cloudfoundry/java-buildpack-dependency-builder/blob/748f2cf74b6b8f66704d8116e512cc806013c9da/openjdk.sh#L21-L39 (e.g. does not seem to yet support Ubuntu xenial, have potentially different test suite excecution policy ...)
   * the java package vendor while including its own CVE automation, results in updates being inconsistent with the ones provided by java buildpack team

Currently java-based CFF projects don't yet seem to leverage java vendor package, and keep the burden of updating the JDK/JRE themselves in their bosh release, sometimes leading to them being vulnerable to Java security CVEs:
   * UAA: https://github.com/cloudfoundry/uaa-release/blob/b24e8e2e0e6a62e4f14f5187a74545733b268a1e/packages/uaa/pre_packaging#L19 is using openjdk-1.8.0_162-x86_64-trusty.tar.gz since in https://github.com/cloudfoundry/uaa-release/commit/1e0db2cb981e5fa8084aa716020d4ac2d8a353f1 (released on [January 2018](http://openjdk.java.net/projects/jdk8u/releases/8u162.html) ). Current security baseline for Java8 according to [Oracle release notes](http://www.oracle.com/technetwork/java/javase/8all-relnotes-2226344.html) is 1.8.0_181-b13 since July 17, 2018 (hopefully consistent with [openjdk policies](http://openjdk.java.net/projects/jdk8u/))
   * Credhub seems [up-to-date](https://github.com/pivotal-cf/credhub-release/blob/10daba5a65f115134e3e085fcffd5f6fa457bff8/packages/credhub/pre_packaging#L9) (using    
 is using openjdk-1.8.0_181.tar.gz) thanks to [automated bumps](https://github.com/pivotal-cf/credhub-release/commits/10daba5a65f115134e3e085fcffd5f6fa457bff8/packages/credhub/pre_packaging) (See related [Story](https://www.pivotaltracker.com/story/show/145737223), unfortunately the related ci repo at https://github.com/pivotal-cf/credhub-ci/ does not yet seem opensource (searched it in [cloudfoundry/](https://github.com/cloudfoundry?utf8=%E2%9C%93&q=credhub&type=&language=) and [cloudfoundry-incubator/](https://github.com/cloudfoundry-incubator?utf8=%E2%9C%93&q=credhub&type=&language=) orgs))

It seems that longtime, mature and maintained automation effort invested into the [java-buildpack-dependency-builder](https://github.com/cloudfoundry/java-buildpack-dependency-builder) could benefit to the CF core teams as well as the community of bosh release authors if could be ported  to the https://github.com/bosh-packages/java-release/

Related community projects that would consume JDK in java vendor package: https://github.com/orange-cloudfoundry/cassandra-boshrelease/issues/12 https://github.com/orange-cloudfoundry/mongodb-boshrelease/issues/22 

I wonder whether this was discussed/considered yet (did not find related traces into [java buildpack tracker](https://www.pivotaltracker.com/n/projects/788065/search?q=vendor))

/CC @cppforlife @fhanik @sreetummidi
/CC @poblin-orange @JCL38-ORANGE

**Comment by sclevine** [comment]
This repo is used to provide Java buildpack releases for cf-deployment. The team that maintains this repo doesn't maintain the Java buildpack or the Java BOSH release.

Maybe the [Java BOSH release issue tracker](https://github.com/bosh-packages/java-release/issues) would be a better place for this request?

**Comment by gberche-orange** [comment]
Sorry @sclevine, I meant to suggest that the Java experience team (which I understand maintains the Java buildpack) could have interest is sharing efforts around OpenJDK JRE and JDK packaging efforts with the https://github.com/bosh-packages/java-release repo. 

I'm certainly happy to move this issue to the java-release repo if this makes more sense, @nebhale you'd prefer proceeding the exchange in https://github.com/bosh-packages/java-release or https://github.com/cloudfoundry/java-buildpack-dependency-builder ?

**Comment by ameyer-pivotal** [comment]
@gberche-orange Go ahead and repost this in https://github.com/bosh-packages/java-release. Thanks!
